import { useRef, useState } from 'react';
import { motion } from 'framer-motion';

export interface AudioExplanationProps {
  audioUrl?: string | null;
  className?: string;
}

export function AudioExplanation({ audioUrl, className }: AudioExplanationProps) {
  const audioRef = useRef<HTMLAudioElement>(null);
  const [playing, setPlaying] = useState(false);

  const toggle = () => {
    const el = audioRef.current;
    if (!el) return;
    if (playing) {
      el.pause();
    } else {
      el.play();
    }
    setPlaying(!playing);
  };

  if (!audioUrl) {
    return (
      <div className={className} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', opacity: 0.5 }}>
        <div style={{ width: '32px', height: '32px', borderRadius: '50%', background: 'var(--glass-border)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>🔇</div>
        <span style={{ fontSize: '0.85rem' }}>Audio unavailable</span>
      </div>
    );
  }

  return (
    <div className={className} style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
      <audio
        ref={audioRef}
        src={audioUrl}
        onEnded={() => setPlaying(false)}
        onPlay={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
      />
      
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={toggle}
        className="glass"
        style={{
          width: '48px',
          height: '48px',
          borderRadius: '50%',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: '1.2rem',
          cursor: 'pointer',
          border: playing ? '2px solid var(--accent-blue)' : '1px solid var(--glass-border)',
          background: playing ? 'rgba(59, 130, 246, 0.1)' : 'var(--glass-bg)',
          color: playing ? 'var(--accent-blue)' : 'var(--text-primary)',
          position: 'relative'
        }}
      >
        {playing && (
          <motion.div
            animate={{ scale: [1, 1.5], opacity: [0.5, 0] }}
            transition={{ repeat: Infinity, duration: 1.5 }}
            style={{
              position: 'absolute',
              inset: -2,
              borderRadius: '50%',
              border: '2px solid var(--accent-blue)',
              zIndex: -1
            }}
          />
        )}
        {playing ? '⏸' : '▶'}
      </motion.button>
      
      <div style={{ display: 'flex', flexDirection: 'column' }}>
        <span style={{ fontSize: '0.9rem', fontWeight: '600' }}>Hear AI Analysis</span>
        <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Generated by ElevenLabs AI Agent</span>
      </div>
    </div>
  );
}
